version: '3.8'

services:
  db:
    image: postgres:13
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: todo-web
    depends_on:
      - db
    restart: always
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PW: password
      POSTGRES_URL: db:5432
      POSTGRES_DB: todoapp
    volumes:
      - .:/app

volumes:
  pgdata:
