version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - check-db
    command: flask run --host=0.0.0.0 --port=5000

  check-db:
    image: postgres:13
    entrypoint: >
      bash -c "
        until pg_isready -h $${DB_HOST} -p $${DB_PORT} -U $${DB_USER}; do
          echo 'Waiting for RDS...'
          sleep 5
        done
      "
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
