global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["54.196.39.221:9100"] # Install node_exporter locally

  - job_name: "postgress_exporter_prod"
    static_configs:
      - targets: ["54.196.39.221:9187"] # If using PostgreSQL exporter

