name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode SSH key
        run: |
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" | base64 --decode > production_key.pem
          chmod 600 production_key.pem

      - name: Deploy Docker container to Production
        run: |
          ssh -o StrictHostKeyChecking=no -i production_key.pem ${{ secrets.PRODUCTION_SSH_USER }}@${{ secrets.PRODUCTION_SERVER }} bash -s <<"EOF"
          set -e

          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-flask-app:latest
          docker network create todo-net || true

          docker stop todo-flask-app || true && docker rm todo-flask-app || true

          docker run -d --name todo-flask-app --network todo-net -p 80:5000 \
            -e DB_HOST=${{ secrets.RDS_HOST }} \
            -e DB_NAME=${{ secrets.RDS_NAME }} \
            -e DB_USER=${{ secrets.RDS_USER }} \
            -e DB_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-flask-app:latest
          EOF

      - name: Clean up SSH key
        run: rm -f production_key.pem
